/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as PublicLoginIndexRouteImport } from './routes/_public/login/index'
import { Route as AuthedTopupIndexRouteImport } from './routes/_authed/topup/index'
import { Route as AuthedSendIndexRouteImport } from './routes/_authed/send/index'
import { Route as AuthedProfileIndexRouteImport } from './routes/_authed/profile/index'
import { Route as AuthedMovementsIndexRouteImport } from './routes/_authed/movements/index'
import { Route as AuthedKycIndexRouteImport } from './routes/_authed/kyc/index'
import { Route as AuthedConvertIndexRouteImport } from './routes/_authed/convert/index'
import { Route as AuthedCardIndexRouteImport } from './routes/_authed/card/index'
import { Route as AuthedBrebKeysIndexRouteImport } from './routes/_authed/breb-keys/index'
import { Route as AuthedAccountsIndexRouteImport } from './routes/_authed/accounts/index'
import { Route as AuthedhomeIndexRouteImport } from './routes/_authed/(home)/index'
import { Route as AuthedAccountsUrnRouteImport } from './routes/_authed/accounts/$urn'
import { Route as AuthedSendColombianBanksIndexRouteImport } from './routes/_authed/send/colombian-banks/index'
import { Route as AuthedSendBloqueFriendsIndexRouteImport } from './routes/_authed/send/bloque-friends/index'
import { Route as AuthedBrebKeysRegisterKeyIndexRouteImport } from './routes/_authed/breb-keys/register-key/index'
import { Route as AuthedBrebKeysPayTransferIndexRouteImport } from './routes/_authed/breb-keys/pay-transfer/index'
import { Route as AuthedBrebKeysPayTransferQrIndexRouteImport } from './routes/_authed/breb-keys/pay-transfer-qr/index'
import { Route as AuthedBrebKeysManageKeysIndexRouteImport } from './routes/_authed/breb-keys/manage-keys/index'
import { Route as AuthedCardDetailsUrnRouteImport } from './routes/_authed/card/details/$urn'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLoginIndexRoute = PublicLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => PublicRoute,
} as any)
const AuthedTopupIndexRoute = AuthedTopupIndexRouteImport.update({
  id: '/topup/',
  path: '/topup/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSendIndexRoute = AuthedSendIndexRouteImport.update({
  id: '/send/',
  path: '/send/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProfileIndexRoute = AuthedProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMovementsIndexRoute = AuthedMovementsIndexRouteImport.update({
  id: '/movements/',
  path: '/movements/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedKycIndexRoute = AuthedKycIndexRouteImport.update({
  id: '/kyc/',
  path: '/kyc/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedConvertIndexRoute = AuthedConvertIndexRouteImport.update({
  id: '/convert/',
  path: '/convert/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCardIndexRoute = AuthedCardIndexRouteImport.update({
  id: '/card/',
  path: '/card/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBrebKeysIndexRoute = AuthedBrebKeysIndexRouteImport.update({
  id: '/breb-keys/',
  path: '/breb-keys/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAccountsIndexRoute = AuthedAccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedhomeIndexRoute = AuthedhomeIndexRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAccountsUrnRoute = AuthedAccountsUrnRouteImport.update({
  id: '/accounts/$urn',
  path: '/accounts/$urn',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSendColombianBanksIndexRoute =
  AuthedSendColombianBanksIndexRouteImport.update({
    id: '/send/colombian-banks/',
    path: '/send/colombian-banks/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedSendBloqueFriendsIndexRoute =
  AuthedSendBloqueFriendsIndexRouteImport.update({
    id: '/send/bloque-friends/',
    path: '/send/bloque-friends/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedBrebKeysRegisterKeyIndexRoute =
  AuthedBrebKeysRegisterKeyIndexRouteImport.update({
    id: '/breb-keys/register-key/',
    path: '/breb-keys/register-key/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedBrebKeysPayTransferIndexRoute =
  AuthedBrebKeysPayTransferIndexRouteImport.update({
    id: '/breb-keys/pay-transfer/',
    path: '/breb-keys/pay-transfer/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedBrebKeysPayTransferQrIndexRoute =
  AuthedBrebKeysPayTransferQrIndexRouteImport.update({
    id: '/breb-keys/pay-transfer-qr/',
    path: '/breb-keys/pay-transfer-qr/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedBrebKeysManageKeysIndexRoute =
  AuthedBrebKeysManageKeysIndexRouteImport.update({
    id: '/breb-keys/manage-keys/',
    path: '/breb-keys/manage-keys/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedCardDetailsUrnRoute = AuthedCardDetailsUrnRouteImport.update({
  id: '/card/details/$urn',
  path: '/card/details/$urn',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedhomeIndexRoute
  '/accounts/$urn': typeof AuthedAccountsUrnRoute
  '/accounts/': typeof AuthedAccountsIndexRoute
  '/breb-keys/': typeof AuthedBrebKeysIndexRoute
  '/card/': typeof AuthedCardIndexRoute
  '/convert/': typeof AuthedConvertIndexRoute
  '/kyc/': typeof AuthedKycIndexRoute
  '/movements/': typeof AuthedMovementsIndexRoute
  '/profile/': typeof AuthedProfileIndexRoute
  '/send/': typeof AuthedSendIndexRoute
  '/topup/': typeof AuthedTopupIndexRoute
  '/login/': typeof PublicLoginIndexRoute
  '/card/details/$urn': typeof AuthedCardDetailsUrnRoute
  '/breb-keys/manage-keys/': typeof AuthedBrebKeysManageKeysIndexRoute
  '/breb-keys/pay-transfer-qr/': typeof AuthedBrebKeysPayTransferQrIndexRoute
  '/breb-keys/pay-transfer/': typeof AuthedBrebKeysPayTransferIndexRoute
  '/breb-keys/register-key/': typeof AuthedBrebKeysRegisterKeyIndexRoute
  '/send/bloque-friends/': typeof AuthedSendBloqueFriendsIndexRoute
  '/send/colombian-banks/': typeof AuthedSendColombianBanksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthedhomeIndexRoute
  '/accounts/$urn': typeof AuthedAccountsUrnRoute
  '/accounts': typeof AuthedAccountsIndexRoute
  '/breb-keys': typeof AuthedBrebKeysIndexRoute
  '/card': typeof AuthedCardIndexRoute
  '/convert': typeof AuthedConvertIndexRoute
  '/kyc': typeof AuthedKycIndexRoute
  '/movements': typeof AuthedMovementsIndexRoute
  '/profile': typeof AuthedProfileIndexRoute
  '/send': typeof AuthedSendIndexRoute
  '/topup': typeof AuthedTopupIndexRoute
  '/login': typeof PublicLoginIndexRoute
  '/card/details/$urn': typeof AuthedCardDetailsUrnRoute
  '/breb-keys/manage-keys': typeof AuthedBrebKeysManageKeysIndexRoute
  '/breb-keys/pay-transfer-qr': typeof AuthedBrebKeysPayTransferQrIndexRoute
  '/breb-keys/pay-transfer': typeof AuthedBrebKeysPayTransferIndexRoute
  '/breb-keys/register-key': typeof AuthedBrebKeysRegisterKeyIndexRoute
  '/send/bloque-friends': typeof AuthedSendBloqueFriendsIndexRoute
  '/send/colombian-banks': typeof AuthedSendColombianBanksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authed/accounts/$urn': typeof AuthedAccountsUrnRoute
  '/_authed/(home)/': typeof AuthedhomeIndexRoute
  '/_authed/accounts/': typeof AuthedAccountsIndexRoute
  '/_authed/breb-keys/': typeof AuthedBrebKeysIndexRoute
  '/_authed/card/': typeof AuthedCardIndexRoute
  '/_authed/convert/': typeof AuthedConvertIndexRoute
  '/_authed/kyc/': typeof AuthedKycIndexRoute
  '/_authed/movements/': typeof AuthedMovementsIndexRoute
  '/_authed/profile/': typeof AuthedProfileIndexRoute
  '/_authed/send/': typeof AuthedSendIndexRoute
  '/_authed/topup/': typeof AuthedTopupIndexRoute
  '/_public/login/': typeof PublicLoginIndexRoute
  '/_authed/card/details/$urn': typeof AuthedCardDetailsUrnRoute
  '/_authed/breb-keys/manage-keys/': typeof AuthedBrebKeysManageKeysIndexRoute
  '/_authed/breb-keys/pay-transfer-qr/': typeof AuthedBrebKeysPayTransferQrIndexRoute
  '/_authed/breb-keys/pay-transfer/': typeof AuthedBrebKeysPayTransferIndexRoute
  '/_authed/breb-keys/register-key/': typeof AuthedBrebKeysRegisterKeyIndexRoute
  '/_authed/send/bloque-friends/': typeof AuthedSendBloqueFriendsIndexRoute
  '/_authed/send/colombian-banks/': typeof AuthedSendColombianBanksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts/$urn'
    | '/accounts/'
    | '/breb-keys/'
    | '/card/'
    | '/convert/'
    | '/kyc/'
    | '/movements/'
    | '/profile/'
    | '/send/'
    | '/topup/'
    | '/login/'
    | '/card/details/$urn'
    | '/breb-keys/manage-keys/'
    | '/breb-keys/pay-transfer-qr/'
    | '/breb-keys/pay-transfer/'
    | '/breb-keys/register-key/'
    | '/send/bloque-friends/'
    | '/send/colombian-banks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts/$urn'
    | '/accounts'
    | '/breb-keys'
    | '/card'
    | '/convert'
    | '/kyc'
    | '/movements'
    | '/profile'
    | '/send'
    | '/topup'
    | '/login'
    | '/card/details/$urn'
    | '/breb-keys/manage-keys'
    | '/breb-keys/pay-transfer-qr'
    | '/breb-keys/pay-transfer'
    | '/breb-keys/register-key'
    | '/send/bloque-friends'
    | '/send/colombian-banks'
  id:
    | '__root__'
    | '/_authed'
    | '/_public'
    | '/_authed/accounts/$urn'
    | '/_authed/(home)/'
    | '/_authed/accounts/'
    | '/_authed/breb-keys/'
    | '/_authed/card/'
    | '/_authed/convert/'
    | '/_authed/kyc/'
    | '/_authed/movements/'
    | '/_authed/profile/'
    | '/_authed/send/'
    | '/_authed/topup/'
    | '/_public/login/'
    | '/_authed/card/details/$urn'
    | '/_authed/breb-keys/manage-keys/'
    | '/_authed/breb-keys/pay-transfer-qr/'
    | '/_authed/breb-keys/pay-transfer/'
    | '/_authed/breb-keys/register-key/'
    | '/_authed/send/bloque-friends/'
    | '/_authed/send/colombian-banks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/login/': {
      id: '/_public/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof PublicLoginIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authed/topup/': {
      id: '/_authed/topup/'
      path: '/topup'
      fullPath: '/topup/'
      preLoaderRoute: typeof AuthedTopupIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/send/': {
      id: '/_authed/send/'
      path: '/send'
      fullPath: '/send/'
      preLoaderRoute: typeof AuthedSendIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profile/': {
      id: '/_authed/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthedProfileIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/movements/': {
      id: '/_authed/movements/'
      path: '/movements'
      fullPath: '/movements/'
      preLoaderRoute: typeof AuthedMovementsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/kyc/': {
      id: '/_authed/kyc/'
      path: '/kyc'
      fullPath: '/kyc/'
      preLoaderRoute: typeof AuthedKycIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/convert/': {
      id: '/_authed/convert/'
      path: '/convert'
      fullPath: '/convert/'
      preLoaderRoute: typeof AuthedConvertIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/card/': {
      id: '/_authed/card/'
      path: '/card'
      fullPath: '/card/'
      preLoaderRoute: typeof AuthedCardIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/breb-keys/': {
      id: '/_authed/breb-keys/'
      path: '/breb-keys'
      fullPath: '/breb-keys/'
      preLoaderRoute: typeof AuthedBrebKeysIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/accounts/': {
      id: '/_authed/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AuthedAccountsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/(home)/': {
      id: '/_authed/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedhomeIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/accounts/$urn': {
      id: '/_authed/accounts/$urn'
      path: '/accounts/$urn'
      fullPath: '/accounts/$urn'
      preLoaderRoute: typeof AuthedAccountsUrnRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/send/colombian-banks/': {
      id: '/_authed/send/colombian-banks/'
      path: '/send/colombian-banks'
      fullPath: '/send/colombian-banks/'
      preLoaderRoute: typeof AuthedSendColombianBanksIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/send/bloque-friends/': {
      id: '/_authed/send/bloque-friends/'
      path: '/send/bloque-friends'
      fullPath: '/send/bloque-friends/'
      preLoaderRoute: typeof AuthedSendBloqueFriendsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/breb-keys/register-key/': {
      id: '/_authed/breb-keys/register-key/'
      path: '/breb-keys/register-key'
      fullPath: '/breb-keys/register-key/'
      preLoaderRoute: typeof AuthedBrebKeysRegisterKeyIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/breb-keys/pay-transfer/': {
      id: '/_authed/breb-keys/pay-transfer/'
      path: '/breb-keys/pay-transfer'
      fullPath: '/breb-keys/pay-transfer/'
      preLoaderRoute: typeof AuthedBrebKeysPayTransferIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/breb-keys/pay-transfer-qr/': {
      id: '/_authed/breb-keys/pay-transfer-qr/'
      path: '/breb-keys/pay-transfer-qr'
      fullPath: '/breb-keys/pay-transfer-qr/'
      preLoaderRoute: typeof AuthedBrebKeysPayTransferQrIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/breb-keys/manage-keys/': {
      id: '/_authed/breb-keys/manage-keys/'
      path: '/breb-keys/manage-keys'
      fullPath: '/breb-keys/manage-keys/'
      preLoaderRoute: typeof AuthedBrebKeysManageKeysIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/card/details/$urn': {
      id: '/_authed/card/details/$urn'
      path: '/card/details/$urn'
      fullPath: '/card/details/$urn'
      preLoaderRoute: typeof AuthedCardDetailsUrnRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAccountsUrnRoute: typeof AuthedAccountsUrnRoute
  AuthedhomeIndexRoute: typeof AuthedhomeIndexRoute
  AuthedAccountsIndexRoute: typeof AuthedAccountsIndexRoute
  AuthedBrebKeysIndexRoute: typeof AuthedBrebKeysIndexRoute
  AuthedCardIndexRoute: typeof AuthedCardIndexRoute
  AuthedConvertIndexRoute: typeof AuthedConvertIndexRoute
  AuthedKycIndexRoute: typeof AuthedKycIndexRoute
  AuthedMovementsIndexRoute: typeof AuthedMovementsIndexRoute
  AuthedProfileIndexRoute: typeof AuthedProfileIndexRoute
  AuthedSendIndexRoute: typeof AuthedSendIndexRoute
  AuthedTopupIndexRoute: typeof AuthedTopupIndexRoute
  AuthedCardDetailsUrnRoute: typeof AuthedCardDetailsUrnRoute
  AuthedBrebKeysManageKeysIndexRoute: typeof AuthedBrebKeysManageKeysIndexRoute
  AuthedBrebKeysPayTransferQrIndexRoute: typeof AuthedBrebKeysPayTransferQrIndexRoute
  AuthedBrebKeysPayTransferIndexRoute: typeof AuthedBrebKeysPayTransferIndexRoute
  AuthedBrebKeysRegisterKeyIndexRoute: typeof AuthedBrebKeysRegisterKeyIndexRoute
  AuthedSendBloqueFriendsIndexRoute: typeof AuthedSendBloqueFriendsIndexRoute
  AuthedSendColombianBanksIndexRoute: typeof AuthedSendColombianBanksIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAccountsUrnRoute: AuthedAccountsUrnRoute,
  AuthedhomeIndexRoute: AuthedhomeIndexRoute,
  AuthedAccountsIndexRoute: AuthedAccountsIndexRoute,
  AuthedBrebKeysIndexRoute: AuthedBrebKeysIndexRoute,
  AuthedCardIndexRoute: AuthedCardIndexRoute,
  AuthedConvertIndexRoute: AuthedConvertIndexRoute,
  AuthedKycIndexRoute: AuthedKycIndexRoute,
  AuthedMovementsIndexRoute: AuthedMovementsIndexRoute,
  AuthedProfileIndexRoute: AuthedProfileIndexRoute,
  AuthedSendIndexRoute: AuthedSendIndexRoute,
  AuthedTopupIndexRoute: AuthedTopupIndexRoute,
  AuthedCardDetailsUrnRoute: AuthedCardDetailsUrnRoute,
  AuthedBrebKeysManageKeysIndexRoute: AuthedBrebKeysManageKeysIndexRoute,
  AuthedBrebKeysPayTransferQrIndexRoute: AuthedBrebKeysPayTransferQrIndexRoute,
  AuthedBrebKeysPayTransferIndexRoute: AuthedBrebKeysPayTransferIndexRoute,
  AuthedBrebKeysRegisterKeyIndexRoute: AuthedBrebKeysRegisterKeyIndexRoute,
  AuthedSendBloqueFriendsIndexRoute: AuthedSendBloqueFriendsIndexRoute,
  AuthedSendColombianBanksIndexRoute: AuthedSendColombianBanksIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface PublicRouteChildren {
  PublicLoginIndexRoute: typeof PublicLoginIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginIndexRoute: PublicLoginIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
